"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";

type RegistrationResponse = { error?: string };

export default function RegistrationPage() {
  const router = useRouter();
  const [formData, setFormData] = useState({ name: "", email: "", password: "" });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => setFormData((current) => ({ ...current, [event.target.name]: event.target.value }));
  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); setError(""); const name = formData.name.trim(); const email = formData.email.trim().toLowerCase(); if (!name || !email || !formData.password) { setError("Заповніть усі обов’язкові поля."); setLoading(false); return; } if (formData.password.length < 8) { setError("Пароль має містити щонайменше 8 символів."); setLoading(false); return; } try { const response = await fetch("/api/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, email, password: formData.password }) }); const result = await response.json() as RegistrationResponse; if (!response.ok) { setError(result.error ?? "Не вдалося створити акаунт."); return; } router.push("/login"); router.refresh(); } catch { setError("Не вдалося з’єднатися із сервером. Спробуйте ще раз."); } finally { setLoading(false); } };
  return <main className="grid min-h-screen place-items-center bg-[radial-gradient(circle_at_90%_0%,#7c3aed,transparent_27%),linear-gradient(135deg,#020617,#172554)] px-4 py-10"><section className="w-full max-w-md rounded-3xl border border-white/15 bg-white p-7 shadow-2xl sm:p-9"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-blue-700 hover:text-blue-900">← На головну</Link><span className="mt-7 grid h-12 w-12 place-items-center rounded-2xl bg-violet-600 text-xl text-white">✦</span><h1 className="mt-5 text-3xl font-black tracking-tight text-slate-950">Створіть акаунт</h1><p className="mt-2 text-slate-500">Збережіть улюблені товари й купуйте швидше.</p><form onSubmit={handleSubmit} className="mt-7 space-y-4">{error && <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm font-medium text-red-700">{error}</p>}<div><label htmlFor="name" className="mb-1.5 block text-sm font-bold text-slate-700">Ім&apos;я</label><input id="name" name="name" type="text" value={formData.name} onChange={handleChange} required autoComplete="name" placeholder="Як до вас звертатися?" className="w-full rounded-xl border border-slate-200 px-4 py-3 text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-violet-500 focus:ring-4 focus:ring-violet-100" /></div><div><label htmlFor="email" className="mb-1.5 block text-sm font-bold text-slate-700">Email</label><input id="email" name="email" type="email" value={formData.email} onChange={handleChange} required autoComplete="email" placeholder="you@example.com" className="w-full rounded-xl border border-slate-200 px-4 py-3 text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-violet-500 focus:ring-4 focus:ring-violet-100" /></div><div><label htmlFor="password" className="mb-1.5 block text-sm font-bold text-slate-700">Пароль</label><input id="password" name="password" type="password" value={formData.password} onChange={handleChange} required minLength={8} autoComplete="new-password" placeholder="Щонайменше 8 символів" className="w-full rounded-xl border border-slate-200 px-4 py-3 text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-violet-500 focus:ring-4 focus:ring-violet-100" /><p className="mt-1.5 text-xs text-slate-400">Використайте щонайменше 8 символів.</p></div><button type="submit" disabled={loading} className="w-full rounded-xl bg-violet-600 py-3.5 font-bold text-white transition hover:bg-violet-700 disabled:cursor-wait disabled:bg-violet-300">{loading ? "Створюємо акаунт…" : "Створити акаунт"}</button></form><p className="mt-6 text-center text-sm text-slate-500">Вже зареєстровані? <Link href="/login" className="font-bold text-violet-700 hover:underline">Увійти</Link></p></section></main>;
}
